### ISSUE TITLE
creatable is not adding items 

### ISSUE THREAD

**Issue by frankforpresident** [iulian-radu-at/react-select-material-ui#23]
In version 6.0.1 the creatable options is not working as expected. It does offer the option to add but once added it does not add the newly created value to the selected options. this issue is mainly focused on the isMultiple but the single mode is also acting weird.

Expected:
When entering a different value than the provided options the dropdown tells the end-user to add the option.
When pressing enter the value is added to the selected items and emitted via the onChange handler. 
When an external source injects a selected value that is not present in the options, the value is visible as selected. 

Actual
The new item is not visible, not when adding it via the dropdown or injecting it

Test:
Same setup as https://github.com/iulian-radu-at/react-select-material-ui/issues/21 but with clearable enabled

Is this because the selected options is not present in the options?

Storybook example of the result
![image](https://user-images.githubusercontent.com/10432797/65973743-203d4d00-e46c-11e9-9f3f-948d8a8161bb.png)

**Comment by ludob78** [comment]
Hello @frankforpresident ,

I had the same issue and I think you are right to asking  if that is because the selected options is not present in the options.

On my side, I fixed it by joining store values with initial select's options to feed options props of MultipleSelect and it works.

**Comment by frankforpresident** [comment]
@ludob78 ,

Alright! Thank for the tip. It would be nice if it's supported natively but I will implementing the workaround.

**Comment by frankforpresident** [comment]
This is the code I used in my wrapper for adding newly created or missing items. Maybe handy for people that are facing the same issue. It also includes sorting but that is not relevant to this ticket.

cc: @iulian-radu-at

```
let options = props.sort ? items.slice().sort(sortByLabel) : [ ...items ];

if (options.some(option => typeof option === 'string')) {
    options = options.map(option => {
      if (typeof option === 'string') {
        return {
          value: option,
          label: option,
        };
      }

      return option;
    });
}

if (value && options.every(option => option && option.value)) {
    const created = (multi ? value : [value]).filter(v => !options.some(option => option && option.value === v));
    options = [...created, ...options];
  }
```

**Comment by iulian-radu-at** [comment]
Base on your comments I assume that you are using the component in a controlled mode. That means that for each change you trigger a render providing the list of options and selected items to ReactSelectMaterialUi.
If you do not add the new option to the already existing options than ReactSelectMaterialUi will filter out all selected options not found in the list of options.
This behavior is correct as the component is used in a controlled way so it is the programmer responsibility to provide the correct set of data. The ReactSelectMaterialUi must not alter the provided data when used in controlled mode (otherwise is no longer a controlled mode but a mix mode).
Is it this use case the one producing problems to you @frankforpresident and @ludob78?

**Comment by iulian-radu-at** [comment]
Closed as no answer from issuer in more than 14 days.
